#cloud-config



package_update: true     # Update the apt database

package_upgrade: true   # Upgrade the instance's packages



apt:

  sources:

    docker.list:

      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable"

      keyid: FFFF0000 # Example GPG key ID



packages:

  - docker-ce



power_state:

  delay: "now"

  mode: reboot

  message: Reboot after installing Docker

  condition: True
