services:
  docs:
    image: cyment_com_local_docs
    container_name: cyment_com_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cyment_com:/app/cyment_com:z
    ports:
      - '9000:9000'
    command: /start-docs
