---
- name: Prepara servidor cyment.com
  hosts: all
  become: true
  vars:
    created_username: acyment

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Restart fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted

  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Import user setup tasks
      ansible.builtin.import_tasks: tasks/user_setup.yml

    - name: Import SSH hardening tasks
      ansible.builtin.import_tasks: tasks/ssh_hardening.yml

    - name: Import Docker tasks
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Import firewall tasks
      ansible.builtin.import_tasks: tasks/firewall.yml

    - name: Import app environment tasks
      ansible.builtin.import_tasks: tasks/app_env.yml

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:

    - name: Import backup tasks
      ansible.builtin.import_tasks: tasks/backup.yml
