def get_country_name(country_code):
    """
    Returns the Spanish name of a country based on its 2-letter ISO code.

    Args:
        country_code: A 2-letter ISO country code (e.g., 'US', 'ES', 'MX')

    Returns:
        The Spanish name of the country or None if the code is not found
    """
    # Dictionary mapping country codes to their Spanish names
    countries = {
        "AF": "Afganistán",
        "AL": "Albania",
        "DE": "Alemania",
        "AD": "Andorra",
        "AO": "Angola",
        "AG": "Antigua y Barbuda",
        "SA": "Arabia Saudita",
        "DZ": "Argelia",
        "AR": "Argentina",
        "AM": "Armenia",
        "AU": "Australia",
        "AT": "Austria",
        "AZ": "Azerbaiyán",
        "BS": "Bahamas",
        "BH": "Bahrein",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BY": "Belarús",
        "BZ": "Belice",
        "BJ": "Benin",
        "BT": "Bhután",
        "BO": "Bolivia (Estado Plurinacional de)",
        "BA": "Bosnia y Herzegovina",
        "BW": "Botswana",
        "BR": "Brasil",
        "BN": "Brunei Darussalam",
        "BG": "Bulgaria",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "BE": "Bélgica",
        "CV": "Cabo Verde",
        "KH": "Camboya",
        "CM": "Camerún",
        "CA": "Canadá",
        "TD": "Chad",
        "CZ": "Chequia",
        "CL": "Chile",
        "CN": "China",
        "CY": "Chipre",
        "CO": "Colombia",
        "KM": "Comoras",
        "CG": "Congo",
        "CR": "Costa Rica",
        "HR": "Croacia",
        "CU": "Cuba",
        "CI": "Côte d'Ivoire",
        "DK": "Dinamarca",
        "DJ": "Djibouti",
        "DM": "Dominica",
        "EC": "Ecuador",
        "EG": "Egipto",
        "SV": "El Salvador",
        "AE": "Emiratos Árabes Unidos",
        "ER": "Eritrea",
        "SK": "Eslovaquia",
        "SI": "Eslovenia",
        "ES": "España",
        "US": "Estados Unidos de América",
        "EE": "Estonia",
        "SZ": "Eswatini",
        "ET": "Etiopía",
        "RU": "Federación de Rusia",
        "FJ": "Fiji",
        "PH": "Filipinas",
        "FI": "Finlandia",
        "FR": "Francia",
        "GA": "Gabón",
        "GM": "Gambia",
        "GE": "Georgia",
        "GH": "Ghana",
        "GD": "Granada",
        "GR": "Grecia",
        "GT": "Guatemala",
        "GN": "Guinea",
        "GQ": "Guinea Ecuatorial",
        "GW": "Guinea-Bissau",
        "GY": "Guyana",
        "HT": "Haití",
        "HN": "Honduras",
        "HU": "Hungría",
        "IN": "India",
        "ID": "Indonesia",
        "IQ": "Iraq",
        "IE": "Irlanda",
        "IR": "Irán (República Islámica del)",
        "IS": "Islandia",
        "CK": "Islas Cook",
        "FO": "Islas Feroe",
        "MH": "Islas Marshall",
        "SB": "Islas Salomón",
        "IL": "Israel",
        "IT": "Italia",
        "JM": "Jamaica",
        "JP": "Japón",
        "JO": "Jordania",
        "KZ": "Kazajstán",
        "KE": "Kenya",
        "KG": "Kirguistán",
        "KI": "Kiribati",
        "KW": "Kuwait",
        "LS": "Lesotho",
        "LV": "Letonia",
        "LR": "Liberia",
        "LY": "Libia",
        "LT": "Lituania",
        "LU": "Luxemburgo",
        "LB": "Líbano",
        "MK": "Macedonia del Norte",
        "MG": "Madagascar",
        "MY": "Malasia",
        "MW": "Malawi",
        "MV": "Maldivas",
        "MT": "Malta",
        "ML": "Malí",
        "MA": "Marruecos",
        "MU": "Mauricio",
        "MR": "Mauritania",
        "FM": "Micronesia (Estados Federados de)",
        "MN": "Mongolia",
        "ME": "Montenegro",
        "MZ": "Mozambique",
        "MM": "Myanmar",
        "MX": "México",
        "MC": "Mónaco",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NI": "Nicaragua",
        "NG": "Nigeria",
        "NU": "Niue",
        "NO": "Noruega",
        "NZ": "Nueva Zelandia",
        "NE": "Níger",
        "OM": "Omán",
        "PK": "Pakistán",
        "PW": "Palau",
        "PA": "Panamá",
        "PG": "Papua Nueva Guinea",
        "PY": "Paraguay",
        "NL": "Países Bajos",
        "PE": "Perú",
        "PL": "Polonia",
        "PT": "Portugal",
        "QA": "Qatar",
        "GB": "Reino Unido de Gran Bretaña e Irlanda del Norte",
        "CF": "República Centroafricana",
        "LA": "República Democrática Popular Lao",
        "CD": "República Democrática del Congo",
        "DO": "República Dominicana",
        "KP": "República Popular Democrática de Corea",
        "TZ": "República Unida de Tanzanía",
        "KR": "República de Corea",
        "MD": "República de Moldova",
        "SY": "República Árabe Siria",
        "RO": "Rumania",
        "RW": "Rwanda",
        "KN": "Saint Kitts y Nevis",
        "WS": "Samoa",
        "SM": "San Marino",
        "VC": "San Vicente y las Granadinas",
        "LC": "Santa Lucía",
        "ST": "Santo Tomé y Príncipe",
        "SN": "Senegal",
        "RS": "Serbia",
        "SC": "Seychelles",
        "SL": "Sierra Leona",
        "SG": "Singapur",
        "SO": "Somalia",
        "LK": "Sri Lanka",
        "ZA": "Sudáfrica",
        "SD": "Sudán",
        "SS": "Sudán del Sur",
        "SE": "Suecia",
        "CH": "Suiza",
        "SR": "Suriname",
        "TH": "Tailandia",
        "TJ": "Tayikistán",
        "TL": "Timor-Leste",
        "TG": "Togo",
        "TK": "Tokelau",
        "TO": "Tonga",
        "TT": "Trinidad y Tabago",
        "TM": "Turkmenistán",
        "TR": "Turquía",
        "TV": "Tuvalu",
        "TN": "Túnez",
        "UA": "Ucrania",
        "UG": "Uganda",
        "UY": "Uruguay",
        "UZ": "Uzbekistán",
        "VU": "Vanuatu",
        "VE": "Venezuela (República Bolivariana de)",
        "VN": "Viet Nam",
        "YE": "Yemen",
        "ZM": "Zambia",
        "ZW": "Zimbabwe",
    }

    # Return the country name or None if not found
    return countries.get(country_code.upper())
