---
- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: false

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types:
      - deb
    uris:
      - https://download.docker.com/linux/ubuntu
    suites:
      - '{{ ansible_distribution_release }}'
    components:
      - stable
    signed_by: /etc/apt/keyrings/docker.asc
    state: present

- name: Upgrade apt
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - curl
      - git
      - ufw
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - fail2ban
      - fish
      - unattended-upgrades
    state: present

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: '{{ created_username }}'
    groups: docker
    append: true
