#cloud-config

package_update: true # Update the apt database

package_upgrade: true # Upgrade the instance's packages

users:
  - name: acyment
    ssh_authorized_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlYRrYQhWO3x/kdyoyBepGsAV+VLYepc+jQX0d4GAuHRzWibN9nq4Ed36dMJLOqrKlerg6kwo4KbqnzIKMnqTnINCrv/VwerE+3s3ECBQzzzLsVHRlUWZMBdWBiNjSTpGkLAi1pRi2yGcA4SJvfTZq5qqICJLYoYapedXvpP1walEQ7VHfzn+mZxn/zvQLE5t3tsNq19VVkSE9aD6RSZqPOEXdS5FLdjLnwjL1FP+6m010HrXtIL6xlZnsxyfRKeYcuILa1aq+I4WY/po+WTwyt++eSGNgsqJG0Zbqs8uhq5JG6CMotO4TNUBgzDrhda5lA4cHPjbcIYMlRoWk0uJhmE5i4KnJrajYyvcRxWDOjBhvPEziUHEAkiJ4GAJMzdnzut4sNnHEBcGzjvcNCsmxg8NZNYQAWSMk3mOurdWCVlqGV/uoJrO0iVwLP88IDkJkcHbuGsp1qoxPfeVIrHVE+hugeMqAd5zP+xmZTWMJD6+rLbg42zLAK/4r1x2Sf70= alan@cyment.com'
    groups: sudo
    shell: /bin/bash

apt:
  sources:
    docker.list:
      source: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable'

      keyid: FFFF0000 # Example GPG key ID

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - unattended-upgrades # Debian/Ubuntu

power_state:
  delay: 'now'

  mode: reboot

  message: Reboot after installing Docker

  condition: True

runcmd:
  - sysctl vm.overcommit_memory=1 # Recommended by redis (https://github.com/jemalloc/jemalloc/issues/1328)
