#cloud-config

package_update: true # Update the apt database

package_upgrade: true # Upgrade the instance's packages

users:
  - name: acyment
    ssh_authorized_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlYRrYQhWO3x/kdyoyBepGsAV+VLYepc+jQX0d4GAuHRzWibN9nq4Ed36dMJLOqrKlerg6kwo4KbqnzIKMnqTnINCrv/VwerE+3s3ECBQzzzLsVHRlUWZMBdWBiNjSTpGkLAi1pRi2yGcA4SJvfTZq5qqICJLYoYapedXvpP1walEQ7VHfzn+mZxn/zvQLE5t3tsNq19VVkSE9aD6RSZqPOEXdS5FLdjLnwjL1FP+6m010HrXtIL6xlZnsxyfRKeYcuILa1aq+I4WY/po+WTwyt++eSGNgsqJG0Zbqs8uhq5JG6CMotO4TNUBgzDrhda5lA4cHPjbcIYMlRoWk0uJhmE5i4KnJrajYyvcRxWDOjBhvPEziUHEAkiJ4GAJMzdnzut4sNnHEBcGzjvcNCsmxg8NZNYQAWSMk3mOurdWCVlqGV/uoJrO0iVwLP88IDkJkcHbuGsp1qoxPfeVIrHVE+hugeMqAd5zP+xmZTWMJD6+rLbg42zLAK/4r1x2Sf70= alan@cyment.com'
    groups: sudo, docker
    shell: /bin/bash

apt:
  sources:
    docker.list:
      source: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable'
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 # Example GPG key ID

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - unattended-upgrades # Debian/Ubuntu

power_state:
  delay: 'now'

  mode: reboot

  message: Reboot after installing Docker

  condition: True

runcmd:
  - usermod -aG docker
  - newgrp docker
  - sysctl vm.overcommit_memory=1 # Recommended by redis (https://github.com/jemalloc/jemalloc/issues/1328)
  - |
    printf "Unattended-Upgrade::Allowed-Origins {\n" > /etc/apt/apt.conf.d/50unattended-upgrades
    printf  "\"\${distro_id}:\${distro_codename}\";\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
    printf   "\"\${distro_id}:\${distro_codename}-security\";\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
    printf   "\"\${distro_id}ESMApps:\${distro_codename}-apps-security\";\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
    printf   "\"\${distro_id}ESM:\${distro_codename}-infra-security\";};\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
    printf   "Unattended-Upgrade::Package-Blacklist {};\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
    printf   "Unattended-Upgrade::DevRelease \"auto\";\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
    printf   "Unattended-Upgrade::Mail \"alan@cyment.com\";\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
    printf   "Unattended-Upgrade::Remove-Unused-Kernel-Packages \"true\";\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
    printf   "Unattended-Upgrade::Remove-New-Unused-Dependencies \"true\";\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
    printf   "Unattended-Upgrade::Remove-Unused-Dependencies \"true\";\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
    printf   "Unattended-Upgrade::Automatic-Reboot \"true\";\n" >> /etc/apt/apt.conf.d/50unattended-upgrades
