# Generated by Django 4.2.11 on 2024-04-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocurso',
            options={'verbose_name_plural': 'Tipos de curso'},
        ),
        migrations.AddField(
            model_name='faqcurso',
            name='tipo_curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cursos.tipocurso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='url_videoconferencia',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='url_whiteboard',
            field=models.URLField(blank=True),
        ),
    ]
