# Generated by Django 5.0.12 on 2025-03-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_tipocurso_stripe_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='id_pago',
        ),
    ]
