# Generated by Django 4.2.11 on 2024-04-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_tipocurso_url_videoconferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocurso',
            name='foto',
            field=models.CharField(max_length=50),
        ),
    ]
