# Generated by Django 4.2.11 on 2024-04-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_tipocurso_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocurso',
            name='foto_tint',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
