# Generated by Django 4.2.11 on 2024-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_tipocurso_foto_tint'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='factura',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='factura',
            name='organizacion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
