# Generated by Django 5.0.12 on 2025-04-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_tipocurso_url_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='organizacion',
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_identificacion_fiscal',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
