# Generated by Django 4.2.11 on 2024-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_factura_organizacion_alter_factura_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
