# Generated by Django 5.0.12 on 2025-04-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_factura_tipo_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='telefono',
        ),
    ]
