# Generated by Django 4.2.11 on 2024-04-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_curso_meeting_id_curso_meeting_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='url_videoconferencia',
            new_name='meeting_url',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='url_whiteboard',
            new_name='whiteboard_url',
        ),
    ]
