# Generated by Django 5.0.12 on 2025-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_remove_factura_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_identificacion_fiscal',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
