# Generated by Django 4.2.11 on 2024-04-25 12:19

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_rename_url_videoconferencia_curso_meeting_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cantidad_dias',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo_usd',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('855'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='curso',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(13, 30)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], default='VIRTUAL', max_length=10),
        ),
    ]
