# Generated by Django 5.0.12 on 2025-04-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_factura_tipo_identificacion_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='id_pago_procesador',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
