# Generated by Django 5.0.12 on 2025-04-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_factura_id_pago_procesador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='id_pago_procesador',
        ),
    ]
