# Generated by Django 4.2.11 on 2024-05-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_curso_cantidad_dias_alter_curso_costo_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocurso',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
