# Generated by Django 4.2.11 on 2024-05-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_tipocurso_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocurso',
            name='orden',
            field=models.IntegerField(unique=True),
        ),
    ]
