# Generated by Django 5.0.12 on 2025-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_remove_factura_id_pago_procesador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_identificacion_fiscal',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
