# Generated by Django 5.0.12 on 2025-04-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_inscripcion_se_envio_mail_bienvenida'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF de la factura generada', upload_to='facturas/pdfs/%Y/%m/%d/', verbose_name='PDF adjunto'),
        ),
    ]
