# Generated by Django 5.0.12 on 2025-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_factura_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='se_envio_mail_facturacion',
            field=models.BooleanField(default=False),
        ),
    ]
