# Generated by Django 5.0.12 on 2025-04-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_factura_se_envio_mail_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_confeccion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
