# Generated by Django 5.0.12 on 2025-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_tipocurso_costo_usd_sin_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='procesador_pago',
            field=models.CharField(choices=[('MP', 'MercadoPago'), ('STRIPE', 'Stripe'), ('TRANSFERENCIA', 'Transferencia')], max_length=13),
        ),
    ]
