# Generated by Django 5.0.12 on 2025-04-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_alter_inscripcion_procesador_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocurso',
            old_name='costo_usd_sin_descuento',
            new_name='costo_sin_descuento_usd',
        ),
        migrations.RenameField(
            model_name='tipocurso',
            old_name='costo_usd_sin_descuento_currency',
            new_name='costo_sin_descuento_usd_currency',
        ),
    ]
