# Generated by Django 5.0.12 on 2025-10-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0025_copy_csm_module_to_cspo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='cc_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
