# Generated by Django 5.0.12 on 2026-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0026_inscripcion_cc_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cc_emails',
            field=models.TextField(blank=True, default='', help_text='Direcciones a copiar (CC) en las facturas de este cliente, separadas por coma.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
