# Generated by Django 5.0.12 on 2026-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0027_cliente_cc_emails_cliente_direccion_cliente_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cc_emails',
            field=models.TextField(blank=True, default='', help_text='Direcciones a copiar (CC) al enviar el mail de facturación, separadas por coma.'),
        ),
    ]
