export const paises = [
  { label: 'Afganistán', value: 'AF' },
  { label: 'Albania', value: 'AL' },
  { label: 'Alemania', value: 'DE' },
  { label: 'Andorra', value: 'AD' },
  { label: 'Angola', value: 'AO' },
  { label: 'Antigua y Barbuda', value: 'AG' },
  { label: 'Arabia Saudita', value: 'SA' },
  { label: 'Argelia', value: 'DZ' },
  { label: 'Argentina', value: 'AR' },
  { label: 'Armenia', value: 'AM' },
  { label: 'Australia', value: 'AU' },
  { label: 'Austria', value: 'AT' },
  { label: 'Azerbaiyán', value: 'AZ' },
  { label: 'Bahamas', value: 'BS' },
  { label: 'Bahrein', value: 'BH' },
  { label: 'Bangladesh', value: 'BD' },
  { label: 'Barbados', value: 'BB' },
  { label: 'Belarús', value: 'BY' },
  { label: 'Belice', value: 'BZ' },
  { label: 'Benin', value: 'BJ' },
  { label: 'Bhután', value: 'BT' },
  { label: 'Bolivia (Estado Plurinacional de)', value: 'BO' },
  { label: 'Bosnia y Herzegovina', value: 'BA' },
  { label: 'Botswana', value: 'BW' },
  { label: 'Brasil', value: 'BR' },
  { label: 'Brunei Darussalam', value: 'BN' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Burkina Faso', value: 'BF' },
  { label: 'Burundi', value: 'BI' },
  { label: 'Egipto', value: 'EG' },
  { label: 'El Salvador', value: 'SV' },
  { label: 'Emiratos Árabes Unidos', value: 'AE' },
  { label: 'Eritrea', value: 'ER' },
  { label: 'Eslovaquia', value: 'SK' },
  { label: 'Eslovenia', value: 'SI' },
  { label: 'España', value: 'ES' },
  { label: 'Estados Unidos de América', value: 'US' },
  { label: 'Estonia', value: 'EE' },
  { label: 'Eswatini', value: 'SZ' },
  { label: 'Etiopía', value: 'ET' },
  { label: 'Federación de Rusia', value: 'RU' },
  { label: 'Fiji', value: 'FJ' },
  { label: 'Filipinas', value: 'PH' },
  { label: 'Finlandia', value: 'FI' },
  { label: 'Francia', value: 'FR' },
  { label: 'Gabón', value: 'GA' },
  { label: 'Gambia', value: 'GM' },
  { label: 'Georgia', value: 'GE' },
  { label: 'Ghana', value: 'GH' },
  { label: 'Granada', value: 'GD' },
  { label: 'Grecia', value: 'GR' },
  { label: 'Guatemala', value: 'GT' },
  { label: 'Guinea', value: 'GN' },
  { label: 'Guinea Ecuatorial', value: 'GQ' },
  { label: 'Guinea-Bissau', value: 'GW' },
  { label: 'Guyana', value: 'GY' },
  { label: 'Haití', value: 'HT' },
  { label: 'Honduras', value: 'HN' },
  { label: 'Hungría', value: 'HU' },
  { label: 'India', value: 'IN' },
  { label: 'Indonesia', value: 'ID' },
  // ... (remaining countries omitted for brevity; keep full list in production)
];
