name: Reusable deploy job

on:
  workflow_call:

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Create production .postgres
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_POSTGRES_HOST: 'postgres'
          envkey_POSTGRES_PORT: 5432
          envkey_POSTGRES_DB: 'cyment_com'
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          directory: .envs/.production
          file_name: .postgres
      - name: Create production .django
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_DJANGO_SETTINGS_MODULE: 'config.settings.production'
          envkey_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          envkey_DJANGO_ADMIN_URL: ${{ secrets.DJANGO_ADMIN_URL }}
          envkey_DJANGO_ALLOWED_HOSTS: '.cyment.com'
          envkey_DJANGO_SECURE_SSL_REDIRECT: 'False'
          envkey_DJANGO_SERVER_EMAIL: ''
          envkey_DJANGO_ACCOUNT_ALLOW_REGISTRATION: 'True'
          envkey_WEB_CONCURRENCY: '4'
          envkey_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          envkey_REDIS_URL: 'redis://redis:6379/0'
          envkey_MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
          envkey_CELERY_FLOWER_USER: ${{ secrets.CELERY_FLOWER_USER }}
          envkey_CELERY_FLOWER_PASSWORD: ${{ secrets.CELERY_FLOWER_PASSWORD }}
          directory: .envs/.production
          file_name: .django
      - name: Create production .webpack
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_MP_PUBLIC_KEY: ${{ secrets.MP_PUBLIC_KEY }}
          directory: .envs/.production
          file_name: .webpack
      - name: Rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --mkpath
          path: ./
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_SSH_HOST }}
          remote_user: ${{ secrets.DEPLOY_SSH_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
