name: Reusable deploying jobs

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: Rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --mkpath
          path: ./
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_SSH_HOST }}
          remote_user: ${{ secrets.DEPLOY_SSH_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
