name: Push

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/_linting.yml

  test:
    uses: ./.github/workflows/_testing.yml

  deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --mkpath --exclude .envs/.production
          path: ./
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_SSH_HOST }}
          remote_user: ${{ secrets.DEPLOY_SSH_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
