name: Push

on:
  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
