name: Push

on:
  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/_linting.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/_testing.yml
    secrets: inherit

  deploy:
    uses: ./.github/workflows/_deploy.yml
    needs: [test, lint]
    secrets: inherit
